In [1]:
import os 
import numpy as np
import earthpy as et

In [2]:
ls ~/earth-analytics/data/earthpy-downloads

avg-monthly-precip.txt  monthly-precip-2002-2013.csv  months.txt


In [4]:
os.chdir(os.path.join(et.io.HOME, "earth-analytics"))

In [5]:
fname = os.path.join("data", "earthpy-downloads", "avg-monthly-precip.txt")

avg_monthly_precip = np.loadtxt(fname)

print(avg_monthly_precip)

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [8]:
fname = os.path.join("data", "earthpy-downloads", "monthly-precip-2002-2013.csv")

precip_2002_2013 = np.loadtxt(fname, delimiter=",")

print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [9]:
avg_monthly_precip.ndim

1

In [10]:
precip_2002_2013.ndim

2

In [11]:
avg_monthly_precip.shape

(12,)

In [12]:
precip_2002_2013.shape

(2, 12)

In [13]:
print(avg_monthly_precip)

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [14]:
avg_monthly_precip *= 25.4

In [20]:
avg_monthly_precip *= 25.4

# avg_monthly_precip = avg_monthly_precip * 25.4

# *=, +=, -=, etc.

print(avg_monthly_precip)


[4.77456771e+09 5.11560826e+09 1.26185004e+10 1.99849763e+10
 2.08034736e+10 1.37780382e+10 1.31641652e+10 1.10497138e+10
 1.25502923e+10 8.93526242e+09 9.48092730e+09 5.72948125e+09]


In [21]:
print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [22]:
precip_2002_2013 *= 25.4

print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [23]:
precip_list = [0.70, 0.75, 1.85, 2.93,3.05,2.02,
               1.93, 1.62, 1.84, 1.31, 0.84]

precip_list *= 25.4

print(precip_list)

TypeError: can't multiply sequence by non-int of type 'float'

In [24]:
mean_avg_precip = np.mean(avg_monthly_precip)

print("mean average monthly precipitation:", mean_avg_precip)

mean average monthly precipitation: 11498750561.224663


In [25]:
median_avg_precip = np.median(avg_monthly_precip)

print("median average monthly precipitation:", median_avg_precip)


median average monthly precipitation: 11800003047.504894


In [26]:
print("minimum average monthly precipitation:", np.min(avg_monthly_precip))
print("maximum average monthly precipitation:", np.max(avg_monthly_precip))

minimum average monthly precipitation: 4774567707.082905
maximum average monthly precipitation: 20803473580.861225


In [27]:
print(precip_2002_2013)

[[ 27.178  11.176  38.1     5.08   81.28   29.972   2.286  36.576  38.608
   61.976  19.812   0.508]
 [  6.858  28.702  43.688 105.156  67.564  15.494  26.162  35.56  461.264
   56.896   7.366  12.7  ]]


In [28]:
print(np.max(precip_2002_2013, axis=0))

[ 27.178  28.702  43.688 105.156  81.28   29.972  26.162  36.576 461.264
  61.976  19.812  12.7  ]


In [29]:
precip_2002_2013_monthly_max = np.max(precip_2002_2013, axis=0)

type(precip_2002_2013_monthly_max)

numpy.ndarray

In [30]:
print(np.max(precip_2002_2013, axis=1))

[ 81.28  461.264]
